### ISSUE TITLE
[BUG] Odd texture found on the Enchanting Table

### ISSUE THREAD

**Issue by Astro-the-Badger** [The-Animonculory/Animonculory-Visual-Overhaul#1]
**Upload your crashlog**

If you've crashed, upload your crashlog from `C:\Users\UserName\Documents\My Games\Skyrim Special Edition`. Reports of crashes that do not include a crashlog will be **ignored and closed.**

**Required: Modlist.txt**

[modlist.txt](https://github.com/The-Animonculory/Animonculory-Visual-Overhaul/files/8241365/modlist.txt)

You must also include your modlist.txt from `C:AVO\Profiles\Animonculory Visual Overhaul`

**Describe the bug**
A clear and concise description of what the bug is. Failure to do this will result in the report being **closed and ignored.**

Upon taking my screenshots, I noticed the Enchanting Table in Dragonsreach had odd wax textures and there were 2 equal sized grey/white rectangles visible on the table's surface.  To make sure this wasn't an isolated incident, I checked two other enchanting tables, found in the Blue Palace and the College of Winterhold.  They both had the same issue.  

**To Reproduce**

1. Go to '...'  Whiterun's Dragonsreach interior, specifically the Enchanting table in the right-most room from the entrance. 
2. Do '...'  Visit the Enchanting Table and see the interesting texture.

**Expected behavior**

I did not expect to see the Enchanting table to have odd wax and two rectangles on it.  Everything else about the table is immaculate. 

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug.

![Game Root42](https://user-images.githubusercontent.com/99372740/158095919-e04c7c04-6033-47b9-b2f3-44a4b5cccc90.png)
![enb2022_3_13_22_04_19](https://user-images.githubusercontent.com/99372740/158097827-7f47db39-43a4-4b36-a71f-264a6b065b7c.jpg)

**Modlist version**

Animonculory Visual Overhaul (AVO)  V.1.0

**Did you add any additional mods?**

I have not altered this modlist in any way.

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
Thanks for the report, I've caaught what this was and will push a hotfix soon.
