### ISSUE TITLE
[BUG] Download error for file CreationKit.ini

### ISSUE THREAD

**Issue by BinarMorker** [The-Animonculory/Animonculory-Visual-Overhaul#11]
**Describe the bug**
While installing the modlist from Wabbajack 3.0.2.3 or 3.0.3.0, the installation stops at the following error:
`Download error for file CreationKit.ini|System.NotImplementedException: The method or operation is not implemented.`

**To Reproduce**

1. In Wabbajack, get the modpack AVO AE
2. Install the modpack normally
3. Wait until everything is downloaded
4. Watch the error and let the dread set in

**Expected behavior**
The modpack should install and maybe not call the Download method in the GameFileDownloader as it is not implemented

**Modlist version**
Latest, so 0.0.1.0 I think?

Anyways, here's some more info:
- Windows 11 Pro (22H2)
- Skyrim AE on Steam (1.6.640.0)
- I'm Premium on Nexus
- I figured it's a problem on the modlist file itself as it calls for downloading the CreationKit.ini file (which doesn't exist in my game folder, and even if I create it and fill it with valid-ish data, it refuses to work)

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***
I have. The list is not for installation bugs :(

**Comment by Althro** [comment]
This is not a bug. You must download the SSE Creation Kit from Steam.

**Comment by Althro** [comment]
The readme for the list now refers to this as well.

**Comment by BinarMorker** [comment]
Got it, thank you very much!
