### ISSUE TITLE
[SUGGESTION] Add correct hashes to modpack

### ISSUE THREAD

**Issue by BinarMorker** [The-Animonculory/Animonculory-Visual-Overhaul#12]
Latest Wabbajack release seems to do hash verification of all the files, which fails the installation of this modpack at the following:

`00:26:56.314 [ERROR] (Wabbajack.InstallerVM) Hashes for mods\CC AE Upgrade\ccbgssse005-goldbrand.bsa file TEMP_BSA_FILES\a89796fd-9177-47c7-801d-f51f5c8a7909\textures\actors\character\facegendata\facetint\ccbgssse005-goldbrand.esl\00000810.dds did not match, expected QyvK0QDvc4w= got 9MYZfxsyPxk=|System.Exception: Hashes for mods\CC AE Upgrade\ccbgssse005-goldbrand.bsa file TEMP_BSA_FILES\a89796fd-9177-47c7-801d-f51f5c8a7909\textures\actors\character\facegendata\facetint\ccbgssse005-goldbrand.esl\00000810.dds did not match, expected QyvK0QDvc4w= got 9MYZfxsyPxk=`

I don't know how the issue should be fixed or if it's even something you can do, but I thought it was worth mentioning so you're aware.

In the meantime, using Wabbajack 3.0.2.3 works wonders and installs the modpack correctly.

Here's the offending release: https://github.com/wabbajack-tools/wabbajack/releases/tag/3.0.3.0

**Comment by BinarMorker** [comment]
Here's the log file:
[Wabbajack.current.log](https://github.com/The-Animonculory/Animonculory-Visual-Overhaul/files/9883297/Wabbajack.current.log)

**Comment by Althro** [comment]
This is a bug with Wabbajack and **not** the list.

Please use an earlier version of Wabbajack to install the list.
