### ISSUE TITLE
[BUG] Many mods are incompatible with the modlist

### ISSUE THREAD

**Issue by kakhulu31** [The-Animonculory/Animonculory-Visual-Overhaul#13]
What's the point of using skse64_1_6_353 for a modlist that's ment to be used as a base for further modifications?
Why not go with 1.5.97 and ae dlcs?

**Comment by chri3i** [comment]
because 1.5 is over a year old by now? feel free to downgrade whatever you want

**Comment by chri3i** [comment]
because 1.5 is over a year outdated by now? feel free to downgrade whatever you want

**Comment by kakhulu31** [comment]
What does it even mean? If it's outdated but superior in every way why would you call it outdated? Isnt 1_6_353 outdated too?

**Comment by chri3i** [comment]
> What does it even mean? If it's outdated but superior in every way why would you call it outdated? Isnt 1_6_353 outdated too?

1.6.353 is outdated as well, but mostly just because nobody had enough time to fully update it yet. If you think you can't play on 1.6.xx, that's fine, means AVO isn't for you. Gotta look for a different base list then. Anyway, this is not a platform for that and the game version of AVO will never be 1.5

**Comment by Althro** [comment]
> What does it even mean? If it's outdated but superior in every way why would you call it outdated? Isnt 1_6_353 outdated too?

1.5.x is **not** superior. It never will be. There is hard evidence that the 1.6.x versions of the game execute better and are stabler. 99% of mods are updated for it as well so there is no point in staying on old versions.

There will be **no** further discussion on this.
