### ISSUE TITLE
[SUGGESTION] Change SOLAS ENB to E.V.C ENB

### ISSUE THREAD

**Issue by polsrepo** [The-Animonculory/Animonculory-Visual-Overhaul#14]
IMHO, it looks considerably better than SOLAS, although YMMV depending on personal preference. In addition, it performs a bit better (about 5 fps on avg) and it's easier to make it compatible with other mods (like AOE for example). It has been updated fairly recently as well.

https://www.nexusmods.com/skyrimspecialedition/mods/71743/?tab=description&jump_to_comment=116703878

**Comment by Althro** [comment]
I meant to switch to that in the most recent update. I'll roll it into the next update which I'm working on 👍🏻
