### ISSUE TITLE
[BUG] Weapon glow between 7AM and 6PM

### ISSUE THREAD

**Issue by polsrepo** [The-Animonculory/Animonculory-Visual-Overhaul#15]
Hello, I'm not including the modlist.txt as I haven't altered the modlist in any way.

Weapons emit a white glow from 7AM to 6PM, specially noticeable on the ground and walls in dark areas (see screenshot with glow)
![489830_20221206094450_1](https://user-images.githubusercontent.com/110729177/205868147-a9793c58-4204-47e5-88e6-2bf252aec603.png)

So far the only way I found to fix this is by selecting "Ignore weather system" under "wetsurfaces" in the enb.ini (see screenshot without glow)
![489830_20221206094456_1](https://user-images.githubusercontent.com/110729177/205868185-bea6a5b9-3e96-44c7-9aa2-c20adea9ec5a.png)

If this is indeed the only way to fix this, I think it would be a good idea to include it in the modlist's readme :)

Cheers!

**Comment by Althro** [comment]
Unable to reproduce this issue.

**Comment by Althro** [comment]
![63](https://user-images.githubusercontent.com/70860633/206022772-b2c5bcce-4b35-4e7b-b5e4-58d5b4fd1811.png)
