### ISSUE TITLE
[BUG] Low poly / low res nordic puzzling stones texture

### ISSUE THREAD

**Issue by polsrepo** [The-Animonculory/Animonculory-Visual-Overhaul#16]
Hello, I'm not including the modlist.txt as I haven't altered the modlist in any way.

I'm not sure if this is intended or not, but the nordic puzzling stones stand out to me in a negative way because of their low poly / low res textures (see screenshot)
![489830_20221205223448_1](https://user-images.githubusercontent.com/110729177/205867962-726787f0-9740-497d-8864-5b3b9e69efea.png)

Cheers!

**Comment by Althro** [comment]
Can confirm this one, will fix for V2.3.1.
