### ISSUE TITLE
[SUGGESTION] Include certain ENB tweking options in the readme

### ISSUE THREAD

**Issue by polsrepo** [The-Animonculory/Animonculory-Visual-Overhaul#17]
Hello,

I think it would be useful to include the following ENB tweaking options from E.V.C's creator in the modlist readme:

> Too saturated/faded/contrast? No problem, you can adjust the image by enabling different LUT presets without leaving the game. To do this, open the in-game ENB menu (HOME key), look to the right side of the menu that appears, open the enbeffect.fx tab, find the TECHNIQUE line and select the desired LUT. This is a powerful enough tool for fine-tuning the image to suit every taste, do not neglect this opportunity.

> ﻿To adjust the brightness of nights and interiors:
> ﻿While in the game, press HOME, look at the right side of the menu that appears, open the enbeffect.fx tab, find the string ﻿Nights & Interior ﻿Adjustors and edit the brightness of nights and interiors as you like.
> ﻿﻿To adjust saturation, Sharp, blur:
> ﻿While in the game, press HOME, look at the right side of the menu that appears, open the enbeffectpostpass.fx tab, and edit ﻿the following ﻿parameters as desired:
> ﻿﻿﻿ - Technicolor2_Saturation (to change the saturation of the image)
> ﻿﻿ - Sharp: amount, Sharp: range (to change the sharpness of the image)
>  ﻿- Blur: amount, Blur: range (to change the blurriness of the image)

**Comment by Althro** [comment]
This already exists: https://github.com/The-Animonculory/Animonculory-Visual-Overhaul#enb-1
