### ISSUE TITLE
[Unable to download archive]

### ISSUE THREAD

**Issue by triffidfood** [The-Animonculory/Animonculory-Visual-Overhaul#22]
Hi,

I'm currently unable to download this mod list because Wabbajack repeatedly hits the following error:

00:00:21.851 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download reshade-shaders-master.zip (HTTPDownloader+State|https://github.com/crosire/reshade-shaders/archive/master.zip)
00:00:21.851 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

I've tried manually downloading the above shaders file from github and moving it to my AVO download location, but this seems to make no difference, so I'm guessing the version or file size don't match the one it's looking for.

I was really hoping to try AVO, so after several hours of otherwise successfully downloading mods via Wabbajack, this is very frustrating!

Any guidance would be really appreciated.

Cheers,
Paul

**Comment by Althro** [comment]
Try this link: https://github.com/crosire/reshade-shaders/archive/a2314cbf9a6c96de4d434b2f9ab8fa9265b8e575.zip

**Comment by HydraX9K** [comment]
I'm having the same problem. The link you provided doesn't work as well. It gives me the same error, "Unable to download reshade-shaders-master.zip (HTTPDownloader+State|https://github.com/crosire/reshade-shaders/archive/master.zip)"

**Comment by triffidfood** [comment]
Yes likewise.  Thanks for the link Althro, but I'm also still encountering the same problem.

Even renaming the file (to "reshade-shaders-master.zip") didn't make any difference, Wabbajack still runs into a fatal error trying to download it.

**Comment by PinoyBloon** [comment]
Uhh.. have you guys tried downloading the file pinned in wabbajack-install-help channel on discord?

**Comment by HydraX9K** [comment]
> Uhh.. have you guys tried downloading the file pinned in wabbajack-install-help channel on discord?

Yeah, it works now. Thanks! Sorry I didn't see that sooner.
