### ISSUE TITLE
[BUG] I can't edit body meshes on bodyslide.

### ISSUE THREAD

**Issue by Fl0mpp** [The-Animonculory/Animonculory-Visual-Overhaul#3]
[modlist.txt](https://github.com/The-Animonculory/Animonculory-Visual-Overhaul/files/8700445/modlist.txt)

whenever I go to bodyslide to change or add presets to my character the preview is missing textures on certain  or has no textures at all and says "no image" around the model, and if I do make a batch build nothing changes in my game both clothes and my character. yes I have changed and added extra mods to the list.

**Comment by Althro** [comment]
This is not a bug and is intended behavour. Bodyslide is setup in a way to allow for it to print to a VFS structure which is what MO2 uses.

Please view a guide on how to use Bodyslide with MO2.
